rpzFile("/opt/powerdns/blocklists/olus-blocklist.rpz")
rpzFile("/opt/powerdns/blocklists/oisd-nsfw.rpz", {ignoreDuplicates = true})
rpzFile("/opt/powerdns/blocklists/hagezy-anti-privacy.rpz", {ignoreDuplicates = true})
rpzFile("/opt/powerdns/blocklists/hagezy-gambling.rpz", {ignoreDuplicates = true})
rpzFile("/opt/powerdns/blocklists/hagezy-multi-normal.rpz", {ignoreDuplicates = true})
rpzFile("/opt/powerdns/blocklists/hagezy-no-safe-search.rpz", {ignoreDuplicates = true})
rpzFile("/opt/powerdns/blocklists/hagezy-threat.rpz", {ignoreDuplicates = true})
